# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.TextField(verbose_name='lista')),
                ('falta', models.DateTimeField(verbose_name='fecha de alta')),
                ('fbaja', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
            ],
            options={
                'verbose_name': 'Clave',
                'verbose_name_plural': 'Claves',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('falta', models.DateTimeField(verbose_name='fecha de alta')),
                ('fbaja', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaRastreos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=10, verbose_name='frecuencia')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripci\xf3n')),
                ('falta', models.DateTimeField(verbose_name='fecha de alta')),
                ('fbaja', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('titulo', models.CharField(max_length=500, verbose_name='t\xedtulo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Rastreos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(verbose_name='Fecha hora')),
            ],
            options={
                'verbose_name': 'Rastreo',
                'verbose_name_plural': 'Rastreos',
            },
        ),
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('falta', models.DateTimeField(verbose_name='fecha de ealta')),
                ('fbaja', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripci\xf3n')),
                ('falta', models.DateTimeField(verbose_name='fecha de alta')),
                ('fbaja', models.DateTimeField(blank=True, null=True, verbose_name='fecha de baja')),
                ('clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.Claves', verbose_name='Id Claves')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.Clientes', verbose_name='Id Clentes')),
                ('frecrastreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.FrecuenciaRastreos', verbose_name='Id FrecuenciaRastreos')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.Sitios', verbose_name='Id Sitios')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddField(
            model_name='rastreos',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.Tareas', verbose_name='Id Tareas'),
        ),
        migrations.AddField(
            model_name='notas',
            name='rastreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_scraper.Rastreos', verbose_name='Id Rastreos'),
        ),
    ]
